spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8787
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: postgres
    password: prodcutservice_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
